# Generated by Django 3.2 on 2021-12-12 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=500)),
                ('product_type', models.CharField(choices=[('plain', 'plain'), ('meter', 'meter')], default='plain', max_length=20)),
                ('availability', models.BooleanField(default=True)),
                ('needing_repair', models.BooleanField(default=False)),
                ('durability', models.IntegerField(default=0)),
                ('max_durability', models.IntegerField(default=0)),
                ('mileage', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('minimum_rent_period', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'product',
            },
        ),
    ]
