# Generated by Django 3.2 on 2021-12-13 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0002_bookingdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingdetails',
            name='actual_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='bookingdetails',
            name='booking_state',
            field=models.CharField(choices=[('running', 'Running'), ('complete', 'complete')], default='running', max_length=10),
        ),
    ]
